# Generated by Django 6.0.4 on 2026-04-20 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Harcama",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200)),
                ("tutar", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("market", "Market"),
                            ("ulasim", "Ulaşım"),
                            ("saglik", "Sağlık"),
                            ("eglence", "Eğlence"),
                            ("fatura", "Fatura"),
                            ("yemek", "Yemek"),
                            ("diger", "Diğer"),
                        ],
                        default="diger",
                        max_length=20,
                    ),
                ),
                ("tarih", models.DateField()),
                ("aciklama", models.TextField(blank=True)),
                ("olusturulma", models.DateTimeField(auto_now_add=True)),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-tarih"],
            },
        ),
    ]
